
// async function example(){
// const myPromise=  new Promise( (resolve,reject)=>
// {
//     let x=1;
//     if(x==1){
      
//      setTimeout(()=>resolve("success"),3000) ;
   
//       }
    
//    else{
//  reject("failure");
//    }

// });
//  await myPromise.then(value=>console.log( value+12)).catch(error=>console.log(error));
// console.log("hello");
// console.log("hello");
// console.log("hello");
// console.log("hello");
//  setTimeout(()=>console.log("end"),3000);

// console.log("hello");
// console.log("hello");
// console.log("hello");
// console.log("hello");
// console.log("hello");
// console.log("hello");
// console.log("hello");
// console.log("hello");

// }

// example();



 function example2(){

 console.log("hello");
 console.log("hello");
 console.log("hello");
 console.log("hello");
 console.log("hello");
 console.log("hello");
 console.log("hello");
example1();
 console.log("hello");
 console.log("hello");
 console.log("hello");
 console.log("hello");
 console.log("hello");
 console.log("hello");
 console.log("hello");
 console.log("hello"); 

}

let x=await setTimeout(()=>console.log("end"),3000);

